--------------------------------------------------------
--  File created - Saturday-June-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FACT_BESTELLUNG
--------------------------------------------------------

  CREATE TABLE "ACH016"."FACT_BESTELLUNG" 
   (	"DIM_KUNDE_KEY" NUMBER(*,0), 
	"DIM_VERKAEUFER_KEY" NUMBER(*,0), 
	"DIM_ARTIKEL_KEY" NUMBER(*,0), 
	"DIM_ARTGRP_KEY" NUMBER(*,0), 
	"DIM_DATUM_KEY" NUMBER(*,0), 
	"ANZAHL" NUMBER(*,0), 
	"PREIS" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ACH016.FACT_BESTELLUNG
SET DEFINE OFF;
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,1,1,28,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,4,2,28,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,5,2,28,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,7,3,28,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,1,1,28,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,28,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,6,2,28,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,28,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,4,7,3,28,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,2,1,28,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,28,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,28,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,3,3,1,28,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,3,4,2,28,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,3,5,2,28,5,2.39);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,3,7,3,28,1,1.59);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,1,1,28,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,28,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,28,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,28,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,28,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,2,1,28,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,4,2,28,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,5,2,28,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,28,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,28,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,28,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,28,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,28,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,28,5,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,28,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (8,3,1,1,29,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (8,3,7,3,29,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (8,3,6,2,29,5,6.29);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,29,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,29,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,29,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,7,3,29,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,1,1,29,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,29,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,6,2,29,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,29,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,4,7,3,29,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,29,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,29,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (3,1,5,2,29,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,3,1,29,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,4,2,29,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,5,2,29,5,2.39);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,7,3,29,1,1.59);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,30,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,30,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,3,7,3,30,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,2,1,30,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,4,2,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,5,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,30,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,30,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,30,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,30,2,6.29);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,4,2,30,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,5,2,30,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,7,3,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,30,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,6,2,30,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,4,7,3,30,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,2,1,30,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,30,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,30,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,3,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,4,2,30,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,5,2,30,5,2.39);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,7,3,30,1,1.59);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,30,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,30,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,3,7,3,30,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,2,1,30,3,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,5,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,30,5,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,30,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,30,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,30,5,6.29);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,4,2,30,3,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,5,2,30,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,7,3,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,30,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,6,2,30,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,7,3,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,4,7,3,30,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,30,10,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,30,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,30,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,3,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,4,2,30,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,5,2,30,5,2.39);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,7,3,30,1,1.59);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,7,3,30,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,30,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,3,7,3,30,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,2,1,30,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,4,2,30,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,5,2,30,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,4,2,30,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,30,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,1,1,30,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,7,3,30,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,30,5,6.29);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,5,2,27,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,7,3,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,27,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,6,2,27,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,4,7,3,27,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,2,1,27,3,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,27,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,3,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,4,2,27,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,5,2,27,5,2.39);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,7,3,27,1,1.59);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,27,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,27,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,3,7,3,27,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,2,1,27,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,4,2,27,1,9.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,5,2,27,2,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,27,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,27,5,6.29);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,5,2,27,3,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,7,3,27,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,27,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,6,2,27,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,4,7,3,27,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,27,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,27,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,3,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,27,5,2.39);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,7,3,27,1,1.59);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,27,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,27,2,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,3,7,3,27,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,2,1,27,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,4,2,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,5,2,27,3,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (6,3,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (6,3,7,3,27,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (6,3,6,2,27,5,6.29);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (7,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (7,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (7,1,5,2,27,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (7,1,7,3,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (8,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (8,1,7,3,27,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (8,1,6,2,27,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (8,1,7,3,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (9,4,7,3,27,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,2,1,27,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,27,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (9,3,3,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (9,3,4,2,27,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (9,3,5,2,27,5,2.39);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (9,3,7,3,27,1,1.59);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,3,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,3,7,3,27,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,3,6,2,27,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,3,7,3,27,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,7,3,27,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,2,1,27,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,5,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,27,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,27,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,1,1,27,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,7,3,31,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,3,6,2,31,5,6.29);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,1,1,31,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,4,2,31,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,5,2,31,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,1,7,3,31,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,1,1,31,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,1,7,3,31,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,6,2,31,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,7,3,31,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (5,4,7,3,31,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,31,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,31,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,5,2,31,5,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,3,1,31,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,4,2,31,2,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,5,2,31,5,2.39);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (2,3,7,3,31,1,1.59);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (8,3,1,1,31,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,7,3,31,5,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (9,2,6,2,31,5,6.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (9,2,7,3,31,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (10,2,7,3,31,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,2,1,31,1,3.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,4,2,31,1,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,5,2,31,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,6,2,31,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,6,2,31,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,6,2,31,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,6,2,31,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,31,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,31,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,31,5,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,4,1,1,31,1,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (4,4,7,3,31,2,1.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,4,6,2,31,5,6.29);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,6,2,32,2,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,2,6,2,32,2,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,32,2,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,3,6,2,32,1,2.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,1,1,32,2,9.99);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,32,10,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,1,4,2,32,3,1.49);
Insert into ACH016.FACT_BESTELLUNG (DIM_KUNDE_KEY,DIM_VERKAEUFER_KEY,DIM_ARTIKEL_KEY,DIM_ARTGRP_KEY,DIM_DATUM_KEY,ANZAHL,PREIS) values (null,4,1,1,32,2,9.99);
--------------------------------------------------------
--  Constraints for Table FACT_BESTELLUNG
--------------------------------------------------------

  ALTER TABLE "ACH016"."FACT_BESTELLUNG" MODIFY ("DIM_VERKAEUFER_KEY" NOT NULL ENABLE);
  ALTER TABLE "ACH016"."FACT_BESTELLUNG" MODIFY ("DIM_ARTIKEL_KEY" NOT NULL ENABLE);
  ALTER TABLE "ACH016"."FACT_BESTELLUNG" MODIFY ("DIM_ARTGRP_KEY" NOT NULL ENABLE);
  ALTER TABLE "ACH016"."FACT_BESTELLUNG" MODIFY ("DIM_DATUM_KEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FACT_BESTELLUNG
--------------------------------------------------------

  ALTER TABLE "ACH016"."FACT_BESTELLUNG" ADD CONSTRAINT "DIM_ARTGRP_FK" FOREIGN KEY ("DIM_ARTGRP_KEY")
	  REFERENCES "ACH016"."DIM_ARTGRP" ("DIM_ARTGRP_KEY") ENABLE;
  ALTER TABLE "ACH016"."FACT_BESTELLUNG" ADD CONSTRAINT "DIM_ARTIKEL_FK" FOREIGN KEY ("DIM_ARTIKEL_KEY")
	  REFERENCES "ACH016"."DIM_ARTIKEL" ("DIM_ARTIKEL_KEY") ENABLE;
  ALTER TABLE "ACH016"."FACT_BESTELLUNG" ADD CONSTRAINT "DIM_DATUM_FK" FOREIGN KEY ("DIM_DATUM_KEY")
	  REFERENCES "ACH016"."DIM_DATUM" ("DIM_DATUM_KEY") ENABLE;
  ALTER TABLE "ACH016"."FACT_BESTELLUNG" ADD CONSTRAINT "DIM_KUNDE_FK" FOREIGN KEY ("DIM_KUNDE_KEY")
	  REFERENCES "ACH016"."DIM_KUNDE" ("DIM_KUNDE_KEY") ENABLE;
  ALTER TABLE "ACH016"."FACT_BESTELLUNG" ADD CONSTRAINT "DIM_VERKAEUFER_FK" FOREIGN KEY ("DIM_VERKAEUFER_KEY")
	  REFERENCES "ACH016"."DIM_VERKAEUFER" ("DIM_VERKAEUFER_KEY") ENABLE;
